### ISSUE TITLE
No info on Dragon

### ISSUE THREAD

**Issue by rnarkus** [Stpo4210/Portere_CSCI2270_FinalProject#4]
i didn't know I had to go back to the start to fight the dragon! I would suggest having the dragons somewhere in the map where you have to fight it and then leave

**Comment by Stpo4210** [comment]
If you look at the node map I've given, you'll see that dragon is on the same node as start. There's no info given on the dragon because you're suppose to wander looking for the dragon, and if you try and fight him without the "Butter Knife" and respond to the question if you'd like to fight the dragon with "n", it'll cout a statement saying that was a good idea and you should find a weapon. It's meant to keep the user guessing as to where they should go and to get them to utilize their markers.
